export const STARTAPPBUFFERRING = "STARTAPPBUFFERRING";
export const STOPAPPBUFFERRING = "STOPAPPBUFFERRING";
export const STARTCATBUFFERRING = "STARTCATBUFFERRING";
export const STOPCATBUFFERRING = "STOPCATBUFFERRING";
export const STARTCATBTNBUFFERRING = "STARTCATBTNBUFFERRING";
export const STOPCATBTNBUFFERRING = "STOPCATBTNBUFFERRING";
