export const LOADINGCATDATAPASS = "LOADINGCATDATAPASS";
export const LOADINGCATDATAFAIL = "LOADINGCATDATAFAIL";
export const ADDCAT = "ADDCAT";
export const ADDSUBCAT = "ADDSUBCAT";
export const ADDSUBSUBCAT = "ADDSUBSUBCAT";
